# Generated by Django 5.0.3 on 2024-05-05 13:31

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=myauth.models.get_user_avatar_path
            ),
        ),
    ]
