# Generated by Django 5.0.3 on 2024-05-11 01:18

import myauth.models
import myauth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=myauth.models.get_user_avatar_path,
                validators=[myauth.validators.SizeValidator(51200)],
            ),
        ),
    ]
