version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      # driver: loki
      # options:
      #  # loki-url: http://localhost:3100/loki/api/v1/push
      #  loki-url: http://host.docker.internal:3100/loki/api/v1/push
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

#  grafana:
#    image: grafana/grafana:11.0.0
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=True
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
# 
#  loki:
#    image: grafana/loki:3.0.0
#    ports:
#      - "3100:3100"
    volumes:
      - ./mysite/database:/app/database
      - ./mysite/log:/app/log
